---
- name: Define OS-specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}.yml"
      # Ansible warns about skip: true deprecation,
      # but errors: ignore seems to need polishing as of 18.06.2019:
      # https://github.com/ansible/ansible/issues/56775
      skip: true
  when: passenger_build_deps is not defined


- name: Install passenger on centos via Phusion RPMs
  include_tasks: phusion_centos_distribution.yml
  when: ansible_distribution == 'CentOS'

- name: Build and install passenger from scratch
  include_tasks: install_from_scratch.yml
  when: ansible_distribution != 'CentOS'

