---
- name: Define build dependencies
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      # Ansible warns about skip: true deprecation,
      # but errors: ignore seems to need polishing as of 18.06.2019:
      # https://github.com/ansible/ansible/issues/56775
      skip: true
  when: passenger_build_deps is not defined

- name: Check if build dependenices are defined
  fail:
    msg: >
      Please define passenger_build_deps for your distribution.

      PRs are welcome at
      https://github.com/timon/ansible-passenger-role/pull/new
  when: passenger_build_deps is not defined

- name: Install passenger build dependencies
  package:
    name: "{{ passenger_build_deps }}"

- name: Install passenger gems
  gem:
    name: "{{ item.gem }}"
    version: "{{ item.version }}"
    executable: "{{ passenger_gem_command }}"
    user_install: false
  loop: "{{ passenger_gems }}"
  notify: passenger rehash rbenv

- name: Get base gem path
  command: "{{ passenger_gem_command }} environment gemdir"
  register: passenger_gem_dir
  changed_when: false

- name: Get passenger version installed
  shell: |
    {{ passenger_gem_command }} list \
      -q passenger -v "{{ passenger_version }}" | \
    sed -E 's/.*\(([^,)]*).*$/\1/'
  register: passenger_version_installed

- name: Set passenger module paths
  set_fact:
    passenger_apache_module_path: "{{ passenger_gem_dir.stdout }}/gems/\
                                   passenger-\
                                   {{ passenger_version_installed.stdout }}/\
                                   buildout/apache2/mod_passenger.so"

- name: Finalize passenger gem installation
  meta: flush_handlers

- name: Build passenger apache module
  command: "/bin/bash -lc \
            'passenger-install-apache2-module --auto \
            --languages={{ passenger_languages }}'"
  args:
    creates: "{{ passenger_apache_module_path }}"

- name: Set passenger configuration template
  command: "/bin/bash -lc \
            'passenger-install-apache2-module --snippet'"
  register: passenger_module_snippet

- name: Check passenger module configured is up to date
  lineinfile:
    dest: "{{ passenger_module_config_path }}"
    line: "LoadModule {{ passenger_apache_module_path }}"
    regexp: "{{ passenger_apache_module_path }}"
  check_mode: true
  ignore_errors: true
  register: passenger_module_loaded

- name: Stub passenger module config
  copy:
    content: "{{ passenger_module_snippet.stdout }}\n"
    dest: "{{ passenger_module_config_path }}"
  notify: restart apache
  when: not passenger_module_loaded or passenger_module_loaded is failed

- include: systemd_tweaks.yml
  notify:
    - "reload systemd"

  # Force flush_handlers so that next apache restart will take place after
  # systemd reload
- meta: flush_handlers

- name: Configure passenger instance registry dir
  lineinfile:
    dest: "{{ passenger_module_config_path }}"
    line: "  PassengerInstanceRegistryDir {{ passenger_registry_dir }}"
    insertbefore: "</IfModule>"
  notify: "restart apache"
