---

- name: Make httpd.service.d directory for systemd
  file:
    path: "{{ apache_service_d }}"
    state: directory

- name: Setup passenger instance registry dir creation on httpd startup
  template:
    src: passenger-instreg-dir.conf.j2
    dest: "{{ apache_service_d }}/passenger-instreg-dir.conf"


