---

- name: Make httpd.service.d directory for systemd
  file:
    path: /etc/systemd/system/httpd.service.d
    state: directory

- name: Setup passenger instance registry dir creation on httpd startup
  template:
    src: passenger-instreg-dir.conf.j2
    dest: /etc/systemd/system/httpd.service.d/passenger-instreg-dir.conf


